### ISSUE TITLE
setsebool for collectd network traffic

### ISSUE THREAD

**Issue by jeremyeder** [jtaleric/browbeat#6]
I ran into an issue with collectd saying that it couldn't connect to the graphite host.  After connecting successfully with nc, I then looked and saw SELinux denials related to collectd.

I then found `setsebool collectd_tcp_network_connect off`.  Enabling that boolean allowed collectd to work.  My confusion is why I don't see that in browbeat anywhere.  Why did I have to do that...

**Comment by akrzos** [comment]
Interesting issue.  

@jeremyeder Do you know if these [tasks](https://github.com/jtaleric/browbeat/blob/master/ansible/install/roles/collectd-generic/tasks/main.yml#L79) in the Ansible playbook for "generic-collectd" ran correctly on collectd install?  

I see two options to address this:
1. Simply blanket address the selinux bool on all collectd installs
2. Determine exactly what each host type (OSPd, OSP Controller, OSP Compute, CFME, OSE, Baremetal, etc...) needs for collectd installs to run with selinux

I am in favor of option 1 right now but option 2 sounds like the long term goal if more selinux issues arise.

**Comment by jeremyeder** [comment]
I didn't use this playbook to install collectd.

**Comment by jtaleric** [comment]
Hey @jeremyeder how did you install collectd? Just from the RPM?

**Comment by jtaleric** [comment]
closing until we get more info.
